AnimationButton コンポーネントを TypeScript に移行
ruritoBlogger/Sanbaka_1.5_fan_site pull request #112
Opened 2020-12-31 17:02 UTC by 0918nobita

related to #111 

できるところから少しずつ

2020-12-31 19:25 UTC, ruritoBlogger commented
![koto](https://user-images.githubusercontent.com/40134104/103423335-617d5900-4be9-11eb-8e52-7188aebbac5e.png)

2020-12-31 19:29 UTC, ruritoBlogger requested changes
propsって別ファイルに分離させた方がいい感じかな...?
フォームとかyoutubeのurlの型は別ファイルに分離させて、今回のような引数の型は同じファイルに書くのが一般的です...よね...?(無知)

2021-01-01 01:50 UTC, 0918nobita commented
Props の定義を別ファイルにわけるのは、普通はしない。
別に難しく考える必要はなくて、まずは各モジュール・コンポーネントの「責務」「知っているべき情報」を整理して、それに基づいてコード分離とかを考えればいい！(これを考えずに DRY 原則を適用しまくって共通処理・共通の型を切り出しまくると、責務も知っているべき情報もぐちゃぐちゃになって大抵破滅する)

実際に `AnimationButton` の Props の型定義をどこに置くかを考えるとき、まずはそもそも `AnimationButton` コンポーネントが「何を知っていて」「何をしなくてはならない」ものなのか整理する。

何をしなくてはならないか：

- 親コンポーネントから Props 経由で渡されたデータを直接HTML要素に埋め込む
- CSS と紐付ける
- 各要素にCSSクラスを設定する

(↑を達成するために)何を知っているべきか：

- 親から Props 経由で何を渡されるか
- 取り込む CSS のパス
- 各CSSクラスの名称

こうやって整理すると、`AnimationButton` と同じモジュールで定義すべきことと、逆に別のモジュールに切り離して `AnimationButton` が「知らない」「する必要がない」ものとすべきことが明確化してくる。
したがって Props の型は `AnimationButton` の Props の型は切り出さずに同じモジュールに記述すべきとわかる。

ちなみに、`AnimationButton` のように「直接与えられたデータだけを使って表示を担当するコンポーネント」を **Presentational Component** という。これに対して、「データ取得・整形・更新等のロジックを含むコンポーネント」を **Container Component** という。コンポーネントの責務を考えるときには、それが Presentational Component なのか Container Component なのかを確認することから始めればいい。

2021-01-01 06:56 UTC, ruritoBlogger commented
勉強になります。ありがとう。

2021-01-01 06:57 UTC, merged