Reactをversion17に更新しました
ruritoBlogger/Sanbaka_1.5_fan_site pull request #117
Opened 2021-01-02 14:46 UTC by ruritoBlogger

chored #114 

## やったこと
- reactのバージョンを16.4 -> 17に更新
- 依存パッケージも更新
- babel.config.jsをreact17に合わせて修正
- tsconfig.jsonをreact17に合わせて修正

## 出来ていないこと
- ソースコードの `import React from 'react'` を削除していない
- productionとdevelopで異なるtypescriptの設定をしていない 参考:(https://zenn.dev/uhyo/articles/react17-new-jsx-transform)

2021-01-02 17:26 UTC, ruritoBlogger commented
設定部分見ていただけると助かります...

2021-01-03 03:05 UTC, 0918nobita requested changes
babel の設定に関しては問題なさそう

ただ、依存ライブラリの更新漏れがあるからそこだけ修正したほうがいいかも (先に自分が確認した感じでは、`react-custom-scrollbars` 以外は React 17 対応が完了していたはず)

- `react-test-renderer`

↑も更新すれば、`yarn` コマンドを叩いたときに出る incorrect peer dependency 警告が `react-custom-scrollbar` に対するもの１つだけに減るはず

2021-01-03 03:20 UTC, 0918nobita commented
余談だけど依存パッケージが増えてくるとそれぞれのバージョンを手動管理するの結構面倒になってくるから、
[renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate) を導入してライブラリが更新されるごとに `package.json` と `yarn.lock` を更新する PR が飛んでくるように設定したほうが楽だと思う (PR 飛ばしてくるタイミングとか細かく設定できる)

lint とテスト走らせる CI もセットアップしとけば「renovate が飛ばしてきた PR をマージするとテストが通らない」みたいな問題に早く気付けるようになる

2021-01-03 06:29 UTC, ruritoBlogger commented
チェックありがとう。
パッケージの更新やります。
renovateの導入はIssue発行します。

2021-01-03 08:39 UTC, ruritoBlogger commented
パッケージの更新やったのでマージします。
確認ありがとう

2021-01-03 08:39 UTC, merged