webpackやbabelの設定ファイルをTSに移行しました
ruritoBlogger/Sanbaka_1.5_fan_site pull request #124
Opened 2021-01-05 08:28 UTC by ruritoBlogger

fixed #115 

## やったこと
- TSで設定ファイル書きたかったので書きました
- Dotenvを使っていなかったので設定ファイルから削除しました

2021-01-05 08:45 UTC, 0918nobita requested changes

2021-01-05 08:45 UTC, 0918nobita commented on package.json
>      "dotenv-webpack": "^3.0.0",
`dotenv-webpack` パッケージは使わなくなったはずなので、remove して良さそう

2021-01-05 08:45 UTC, 0918nobita commented on babel.config.ts
> +    ['@babel/preset-react', { targets: { node: 'current' }, runtime: 'automatic' },],
1行に縮めて書くオブジェクトリテラルのメンバには、ケツカンマをつけないのが普通だと思う (この書き方が好みなら無視しておｋ

2021-01-06 06:18 UTC, ruritoBlogger commented on package.json
>      "dotenv-webpack": "^3.0.0",
それはそう

2021-01-06 06:19 UTC, ruritoBlogger commented on babel.config.ts
> +    ['@babel/preset-react', { targets: { node: 'current' }, runtime: 'automatic' },],
なるほどな...
この書き方は好みじゃないのでさよならしときます

2021-01-06 06:20 UTC, ruritoBlogger commented
修正終わったのでマージします〜
プルリクチェックしてくれてありがとう

2021-01-06 06:20 UTC, merged