TypeScript用にEslintの環境を整えました
ruritoBlogger/Sanbaka_1.5_fan_site pull request #125
Opened 2021-01-05 09:12 UTC by ruritoBlogger

fixed #116 

## やったこと
- TypeScript用のeslintプラグインを導入しました
- eslintの設定を変更しました
- eslintの範囲にtsを含めるように変更しました

2021-01-05 09:49 UTC, 0918nobita requested changes

2021-01-05 09:49 UTC, 0918nobita commented on .eslintrc.js
> +    project: ['./tsconfig.eslint.json']
`tsconfig.eslint.json` を使わずに、既存の `tsconfig.json` を使う↓みたいな設定で良いんじゃないかな…？(もし意図的に設定ファイルを分けてるなら理由を教えてほしい、他の解決法を提案できるかもしれないから

```typescript
module.exports = {
  ...
  parserOptions: {
    sourceType: 'module',
    tsconfigRootDir: __dirname,
    project: './tsconfig.json'.
  },
  ...
};
```

2021-01-05 09:49 UTC, 0918nobita commented on .eslintrc.js
> -    'import',
(これは別の PR で対応することにしてもいいと思うけど一応)
`eslint-plugin-import` は TypeScript にも対応してて、↓のように extends を設定するだけで移行できるはず

```typescript
module.exports = {
  ...
  extends: [
    ...
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
    ...
  ],
  ...
};
```

参考：https://github.com/benmosher/eslint-plugin-import#typescript

2021-01-05 09:49 UTC, 0918nobita commented on .eslintrc.js
> -    'react',
`eslint-plugin-react` は、extends に `plugin:react/recommended` を追加するだけで TS / JS の両方に対して設定できたはず

参考：https://github.com/yannickcr/eslint-plugin-react#configuration

2021-01-05 09:58 UTC, 0918nobita commented
ESLint の設定はいろいろつらみがあると思うけど頑張ってほしい
ちなみに自分は普段 JS / TS 両方を ESLint でチェックできるように overrides オプションを設定してる
https://github.com/0918nobita/vision/blob/20e25e488a087949c5bb3932331852be08e85b5e/.eslintrc.js

2021-01-06 06:26 UTC, ruritoBlogger commented on .eslintrc.js
> +    project: ['./tsconfig.eslint.json']
この部分は参考サイトをほぼ移植してる(tsconfig.jsonで代用が効くことを知らなかった)のでtsconfig.jsonに統一します

2021-01-06 06:52 UTC, ruritoBlogger commented on .eslintrc.js
> -    'import',
なるほど...
削除したプラグインの情報見に行ったら大体extendsで突っ込めそうだったので入れてみます
ありがとう

2021-01-06 06:52 UTC, ruritoBlogger commented on .eslintrc.js
> -    'react',
https://github.com/ruritoBlogger/Sanbaka_1.5_fan_site/pull/125#discussion_r552400313
と同じ感じです。ありがとう。

2021-01-06 07:28 UTC, ruritoBlogger commented
eslintの設定とてもつらい...
overrideを設定するとjs + 対象の拡張子のファイル(今回はts, tsx)も含まれる感じか...
とりあえず試してみます〜

2021-01-06 10:03 UTC, ruritoBlogger commented
設定変更してeslintが走るのを確認出来たのでマージします。
確認してくれてありがとう

2021-01-06 10:03 UTC, merged